spring.application.name=codecase_web

server.port=9001
# Niveau de logging
logging.level.root=error
# pour le package
logging.level.fr.swif.codecase_web=info
# pour la BDD
logging.level.org.springframework.data=INFO
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
# Niveau de logging pour TOMCAT
logging.level.org.springframework.boot.web.embedded.tomcat=INFO

# Pour que les logs soient enregistrés dans un fichier
logging.file.name=logs/codecase-web.log

fr.swif.codecase-web.appweb.apiUrl=http://localhost:9002

# Pour la JWT
app.secret-key=!&%{T;bKtj?GO0|;)_daYEbBpo4!Aj;WKY,LHXEv53t